---
- name: Conditional Playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install MariaDB Server 10.3
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: apache2
      state: present
    notify: Restart MariaDB 10.3



  handlers:
  
  - name: Restart MariaDB 10.3
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    systemd:
      name: apache2
      state: restarted
...