---
- name: User playbook
  hosts: all
  become: true
  become_method: sudo 
  tasks:
  - name: Add the users
    ansible.builtin.user:
      name: "{{ item }}"
    with_items:
    - Bob
    - ben
    - lisa
    - katty


...
