- name: User playbook
  hosts: all
  become: true
  become_method: sudo 
  tasks:
  - name: Add the users
    ansible.builtin.user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    with_items:
    - Bob
    - ben
    - lisa
    - katty
    
  - name: Download url
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/Bob/
      
  - name: Download url
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/ben/
  
  - name: Download url
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/lisa/

  - name: Download url
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/katty/
- name: Conditional Playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install MariaDB Server 10.3
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: apache2
      state: present
    notify: Restart MariaDB 10.3



  handlers:
  
  - name: Restart MariaDB 10.3
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    systemd:
      name: apache2
      state: restarted