
- name: Install wordpress
  hosts: all
  become: true
  become_method: sudo 
  vars:
    wordpress_version: "4.0.32"
    php_version: "5.4.16"
  tasks:
  - name: Get wordpress 
    get_url:
      url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      mode: '0440'
  - name: Install telnet
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: telnet
      state: present
  - name: Ensure group "devops" exists
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04" 
    ansible.builtin.group:
      name: devops
      state: present
  - name: Add users
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04" 
    ansible.builtin.user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    with_items:
    - Bob
    - ben
    - lisa
    - katty
    - johnd
  - name: adding existing user '{{ item }}' to group devops
    user:
       name: "{{ item }}"
       groups: devops
       append: yes
    with_items:
     - Bob
     - ben
     - lisa
     - katty
     - johnd